
trigger:
- master

pool:
  vmImage: windows-latest


steps:

- task: VSBuild@1
  inputs:
    solution: '**libMon\*.sln'
    vsVersion: '16.0'
    platform: 'x64'
    configuration: 'Debug'

- task: CmdLine@2
  inputs:
    script: |
      echo Test Start 

      ls

      cd libMon
      cd x64
      cd Debug
    
      CppUnitTest.exe -1 32 -100 100
      
      echo Test Done
    failOnStderr: true