
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: VSBuild@1
  inputs:
    solution: '**libMon\*.sln'
    vsVersion: '16.0'
    platform: 'x64'
    configuration: 'Debug'
    msbuildArchitecture: 'x64'
    createLogFile: True

- task: CmdLine@2
  inputs:
    script: |
      echo Test Start 

      echo $(Build.SourcesDirectory)
      cd $(Build.SourcesDirectory)
      ls

      cd libMon
      cd x64
      cd Debug
    
      CppUnitTest.exe -1 32 -100 100
      
      echo Test Done
    failOnStderr: true