
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: MSBuild@1
  inputs:
    solution: '**\libMon\*.sln'
    vsVersion: '16.0'
    platform: 'x64'
    configuration: 'Debug'
    clean: true
    msbuildArchitecture: 'x64'
